org.gradle.jvmargs  = -Xmx1G

# Fabric properties
minecraft_version   = 1.21.6-pre1
yalmm_version       = 10
parchment_version   = 2024.07.07
loader_version      = 0.16.14

# Mod properties
mod_version         = 1.4.0-rc.1+1.21.6
maven_group         = io.github.queerbric

# Dependencies
fabric_api_version  = 0.125.2+1.21.6
