org.gradle.jvmargs  = -Xmx1G

# Fabric properties
minecraft_version   = 1.21.5
yalmm_version       = 14
parchment_version   = 2024.07.07
loader_version      = 0.16.14

# Mod properties
mod_version         = 1.3.1+1.21.5
maven_group         = io.github.queerbric

# Dependencies
fabric_api_version  = 0.118.6+1.21.5
