# Gradle Settings
org.gradle.jvmargs=-Xmx1G
org.gradle.configuration-cache=true

# Project properties
group=io.github.queerbric
version=1.4.4+1.21.8
java_version=21

# Fabric properties
yalmm_version       = 3
parchment_version   = 2024.07.07

# Mod properties
mod_version         = 1.4.1+1.21.8

# Dependencies
fabric_api_version  = 0.127.0+1.21.6
