[versions]
minecraft = "26.2-pre-1"
fabric-loader = "0.19.2"
neoforge-loader = "11.0.13"
neoforge-api = "26.1.2.67-beta"

# Dependencies
yumi-mc-foundation = "1.1.0+26.2-pre-1"

# Gradle
gradle-licenser = "4.0.+"
gradle-loom = "1.16.+"
gradle-lambdamcdev = "2.0.+"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
neoforge-loader = { module = "net.neoforged.fancymodloader:loader", version.ref = "neoforge-loader" }
neoforge-api = { module = "net.neoforged:neoforge", version.ref = "neoforge-api" }

# Dependencies
yumi-mc-foundation = { module = "dev.yumi.mc.core:yumi-mc-foundation", version.ref = "yumi-mc-foundation" }

# Gradle
gradle-loom = { module = "net.fabricmc:fabric-loom", version.ref = "gradle-loom" }
gradle-lambdamcdev = { module = "dev.lambdaurora.mcdev:dev.lambdaurora.mcdev.gradle.plugin", version.ref = "gradle-lambdamcdev" }

[plugins]
loom = { id = "net.fabricmc.fabric-loom", version.ref = "gradle-loom" }
lambdamcdev = { id = "dev.lambdaurora.mcdev", version.ref = "gradle-lambdamcdev" }
