[versions]
minecraft = "26.1-pre-2"
fabric-loader = "0.18.4"
neoforge-loader = "10.0.34"

# Dependencies
yumi-mc-foundation = "1.0.0-beta.2+26.1-pre-2"

# Gradle
gradle-licenser = "2.2.+"
gradle-loom = "1.15.+"
gradle-lambdamcdev = "1.8.+"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
neoforge-loader = { module = "net.neoforged.fancymodloader:loader", version.ref = "neoforge-loader" }

# Dependencies
yumi-mc-foundation = { module = "dev.yumi.mc.core:yumi-mc-foundation", version.ref = "yumi-mc-foundation" }

# Gradle
gradle-loom = { module = "net.fabricmc:fabric-loom", version.ref = "gradle-loom" }
gradle-lambdamcdev = { module = "dev.lambdaurora.mcdev:dev.lambdaurora.mcdev.gradle.plugin", version.ref = "gradle-lambdamcdev" }

[plugins]
loom = { id = "net.fabricmc.fabric-loom", version.ref = "gradle-loom" }
lambdamcdev = { id = "dev.lambdaurora.mcdev", version.ref = "gradle-lambdamcdev" }
